name: Update Statuses

on:
  schedule:
    - cron: "0 */6 * * *"   # каждые 6 часов
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i cheerio@1.0.0-rc.12

      - name: Run update script
        run: node scripts/update.js

      - name: Commit & push if changed (with rebase)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes"; exit 0
          fi
          git add data/statuses.json
          git commit -m "chore: update statuses"
          git pull --rebase origin "$BRANCH"
          git push origin HEAD:"$BRANCH"
