name: Update Statuses

# This workflow periodically checks the upstream khoindvn.io.vn site to
# determine whether KSign and eSign are available (based on the presence
# of checkmark icons in the HTML) and updates the local data/statuses.json
# accordingly. It runs every 6 hours and can also be triggered manually.

on:
  schedule:
    # Every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run update script
        run: node scripts/update.js
      - name: Commit and push if data changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [[ $(git status --porcelain) ]]; then
            git add data/statuses.json
            git commit -m "chore: update statuses"
            git push
          fi
